### ISSUE TITLE
网易博客foundNextBlogPermalink函数失效的问题

### ISSUE THREAD

**Issue by wellsleep** [crifan/BlogsToWordpress#1]
Hi 

虽然估计你不打算维护这个工具了，还是报一下问题。
`foundNextBlogPermalink = re.search(r",nextBlogPermalink:\"(?P<nextBlogPermalink>blog/static/\d+)\",", blogsDwrRespHtml);`
不熟正则表达，我猜你是想在返回的页面里找`nextBlogPermalink`字段，然后把网址抠出来，作为`foundNextBlogPermalink`的字段。

但现在的网页里已经没有`nextBlogPermalink`字段了，取而代之的是`$_newOldBlogLinkTopDiv`，而且一行有两个网址，一个前一篇，一个后一篇，不过可以通过比较数字的大小来判读后一篇的网址。

不知道你会不会更新，我先自己改改试试。

还是很感谢其他部分的贡献，虽然目前只能下载最初的一篇，但至少那一篇的格式输出似乎没有问题。

**Comment by crifan** [comment]
@wellsleep 我现在还是继续维护此工具的。
请把出错的网易博客的地址给我，我好测试并解决问题。

**Comment by wellsleep** [comment]
博客地址：anotherwellsleep.blog.163.com

不过我debug了一下，发现你可能之前是想用一个简便的办法直接从链接里直接下载而不是载入完整html之后再截取，因为soup的代码其实被注释掉了。
[L1576](https://github.com/crifan/BlogsToWordpress/blob/9ee69ed41052b2f624d3bd3a0d3e5f646bbbafbc/libs/crifan/blogModules/BlogNetease.py#L1576)

现在的问题是如果不用soup，只能下载到最老的一片博客。如果用soup，我不知道是不是网易博客反爬虫还是怎样，下载几百篇之后就会出错，打开出错链接所显示的页面，在博文的顶上会显示“文章含违规内容，需要输入验证码”。然而其实任何敏感内容都没有，输完验证码，从头再来，就可以继续下去。

试用了一个叫blog_backup的软件，没交注册费，试用了一下似乎下载都没问题。略微研究~反向~了一下，他也是python脚本拖的，不知道有什么诀窍。而且blog_backup的速度非常快，似乎是直接读取的blog列表，不是一篇篇拖下来正则解析。

**Comment by crifan** [comment]
@wellsleep 花了时间去调试半天，最后结论是：
用我的脚步去导出你的博客：
`BlogsToWordpress.py -s http://anotherwellsleep.blog.163.com`
并没有问题，可以正常导出啊：
![](http://or65gc2qf.bkt.clouddn.com/17-11-12/7302288.jpg)
你再去试试。

**Comment by wellsleep** [comment]
之前我是在win 10 x64下用命令行跑的，跑的py脚本。我看你的博客下面也有人反映这个问题（最顶上一条）：
https://www.crifan.com/crifan_released_all/website/python/blogstowordpress/before_use/

在linux上也是同样结果（内核4.8.0 64b，python 2.7.13），
直接git clone，```python BlogToWordpress.py -s http://anotherwellsleep.blog.163.com```
```bash
2017/11/13 11:03:41 LINE 895  INFO      Title = 好累！
2017/11/13 11:03:41 LINE 908  ERROR   Can not extract post content for http://anotherwellsleep.blog.163.com/blog/static/218746151200502910010317 !
2017/11/13 11:03:41 LINE 1901 ERROR   Unknown Error !
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1899, in <module>
    main()
  File "BlogsToWordpress.py", line 1651, in main
    infoDict = fetchSinglePost(permalink);
  File "BlogsToWordpress.py", line 909, in fetchSinglePost
    sys.exit(2);
SystemExit: 2
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1902, in <module>
    raise Exception("Unknown Error !")
Exception: Unknown Error !
```
等我回头再用mac试试。  

--------
试了一下win 10中的bash（小linux内核），前几条正常，没有出现纯linux上的问题。会是依赖的问题？

**Comment by wellsleep** [comment]
最后回报一下，win 10的bash中成功运行完整个博客站的下载。使用命令：
```bash
python BlogToWordpress.py -s http://ADDRESS -g no
```
整个过程中遇到的问题总结：
1. win 10命令行（cmd）中无法运行，第一篇下载后提示出错（使用py脚本为上一个更新的版本，WXR为一个文件。和许多人反应的一样，第一篇博客下载完成后会去下载“心情随笔”，然后出错。使用被注释掉的soup方式可以下载，但下载一段时间之后可能会触发反爬虫。未测试`-g no`的选项。）；
2. Linux（内核4.8.0，64位Kali发行版，Python 2.7.13），第一篇都无法下载，错误内容见上一个post；
3. 使用win 10 bash命令行成功下载所有的文章，每篇文章一个xml文件。中间曾经出现过错误，但加上`-g no`选项就通过了。
```bash
$ uname -r
4.4.0-43-Microsoft
$ python --version
Python 2.7.6
```
4. 如果要用登录模式`-u` `-p`下载文章，得用浏览器登录，有了cookie才行。

如果你需要的话，我可以帮忙试下mac的情况，不过我的mac os还停在El Captain……

**Comment by crifan** [comment]
@wellsleep 你要是有空的话，可以帮忙测试一下登录后的情况。
不过：
1. 我最近有点忙，估计没时间和你一起抽空调试
2. 貌似用登录模式的人也很少吧 -》 至少都放开为公开查看，导出后再设置为隐私，也是可行的。😂

**Comment by wellsleep** [comment]
@crifan 登录后下载是可行的，需要浏览器里现有cookie，再用脚本登录就好。
不过不知为何其他功能有时候还是不太稳定... 
比如有没有`-g`或者`-x`对于下载能不能成功，影响还挺大。刚开始没有带`-g`，导入到markdown文本的时候中文标题乱成了一锅粥，后来也就忍了就这样吧，拖一遍得一个来小时...

**Comment by crifan** [comment]
@wellsleep 加了`-g yes`，是`启用翻译`
>现在是用 [有道智云](http://fanyi.youdao.com/openapi)的API去翻译的。 
> -》 但是翻译功能只是把中文标题，翻译为wordpress的`slug`==`postname`，不是文章标题啊。
> 对于你的中文标题，不应该有影响才对。

`-x`是指定输出的单个xml最大值，默认是2MB。
